#!/bin/sh
set -e

# NOTE: This script is run as root. Any files created here should have owner set to 'node'.

DATA_DIR="${LIBREFANG_HOME:-/data}"
CONFIG="$DATA_DIR/config.toml"

mkdir -p "$DATA_DIR"

# Fix permissions on the data directory if it is not owned by 'node' user
if [ "$(stat -c '%U' "$DATA_DIR" 2>/dev/null)" != "node" ]; then
  chown -R node:node "$DATA_DIR"
fi

# Auto-generate config.toml on first boot if missing
if [ ! -f "$CONFIG" ]; then

  # Detect best available provider from env vars
  if [ -n "$OPENROUTER_API_KEY" ]; then
    PROVIDER="openrouter"
    MODEL="${LIBREFANG_MODEL:-openrouter/stepfun/step-3.5-flash:free}"
    KEY_ENV="OPENROUTER_API_KEY"
  elif [ -n "$GROQ_API_KEY" ]; then
    PROVIDER="groq"
    MODEL="${LIBREFANG_MODEL:-llama-3.3-70b-versatile}"
    KEY_ENV="GROQ_API_KEY"
  elif [ -n "$ANTHROPIC_API_KEY" ]; then
    PROVIDER="anthropic"
    MODEL="${LIBREFANG_MODEL:-claude-sonnet-4-20250514}"
    KEY_ENV="ANTHROPIC_API_KEY"
  elif [ -n "$OPENAI_API_KEY" ]; then
    PROVIDER="openai"
    MODEL="${LIBREFANG_MODEL:-gpt-4o}"
    KEY_ENV="OPENAI_API_KEY"
  elif [ -n "$DEEPSEEK_API_KEY" ]; then
    PROVIDER="deepseek"
    MODEL="${LIBREFANG_MODEL:-deepseek-chat}"
    KEY_ENV="DEEPSEEK_API_KEY"
  elif [ -n "$GEMINI_API_KEY" ]; then
    PROVIDER="gemini"
    MODEL="${LIBREFANG_MODEL:-gemini-2.5-flash}"
    KEY_ENV="GEMINI_API_KEY"
  else
    PROVIDER="openrouter"
    MODEL="openrouter/stepfun/step-3.5-flash:free"
    KEY_ENV="OPENROUTER_API_KEY"
  fi

  # Railway/Render inject PORT env var; default to 4545
  LISTEN_PORT="${PORT:-4545}"

  cat > "$CONFIG" <<EOF
# Auto-generated by LibreFang Docker entrypoint
api_listen = "0.0.0.0:${LISTEN_PORT}"
log_level = "info"

[default_model]
provider = "$PROVIDER"
model = "$MODEL"
api_key_env = "$KEY_ENV"

[memory]
decay_rate = 0.05
EOF
  chown node:node "$CONFIG"
  echo "Generated $CONFIG (provider=$PROVIDER, model=$MODEL, port=$LISTEN_PORT)"
fi

# If PORT is set (Railway/Render), override api_listen in existing config
if [ -n "$PORT" ]; then
  sed -i "s|^api_listen = .*|api_listen = \"0.0.0.0:${PORT}\"|" "$CONFIG"
  chown node:node "$CONFIG"
fi

# Auto-sync registry content (agents, hands, skills, providers) on boot
# Uses HTTP tarball download if git is unavailable
gosu node librefang init 2>/dev/null || true

exec gosu node "$@"
