//! Core channel bridge types.

use chrono::{DateTime, Utc};
use librefang_types::agent::AgentId;
use librefang_types::config::AutoRouteStrategy;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::pin::Pin;

use async_trait::async_trait;
use futures::Stream;
use tokio::sync::mpsc;

/// The type of messaging channel.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ChannelType {
    Telegram,
    WhatsApp,
    Slack,
    Discord,
    Signal,
    Matrix,
    Email,
    Teams,
    Mattermost,
    WeChat,
    WebChat,
    CLI,
    Custom(String),
}

/// A user on a messaging platform.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelUser {
    /// Platform-specific user ID.
    pub platform_id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Optional mapping to an LibreFang user identity.
    pub librefang_user: Option<String>,
}

/// A known member of a group chat, accumulated from past messages.
///
/// Used to populate multi-user context in the system prompt so agents can
/// distinguish between the current sender and other users mentioned in a
/// message (e.g. `@pepe`, `@jose`).
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct GroupMember {
    /// Platform-specific user ID.
    pub user_id: String,
    /// Human-readable display name (what the platform shows).
    pub display_name: String,
    /// Optional `@handle` for platforms that expose one (Telegram, Discord, ...).
    #[serde(default)]
    pub username: Option<String>,
}

/// Typing indicator event from a channel.
#[derive(Debug, Clone)]
pub struct TypingEvent {
    pub channel: ChannelType,
    pub sender: ChannelUser,
    pub is_typing: bool,
}

/// A single interactive button in a message.
///
/// Platform-agnostic representation used by Telegram inline keyboards,
/// Slack Block Kit buttons, and Feishu interactive card actions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InteractiveButton {
    /// Human-visible button label.
    pub label: String,
    /// Callback data string sent back when the button is clicked.
    /// Must be ≤ 64 bytes for Telegram compatibility.
    pub action: String,
    /// Optional style hint: `"primary"`, `"danger"`, etc.
    /// Interpretation is platform-specific.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// Optional URL to open when the button is clicked (instead of a callback).
    /// Mutually exclusive with `action` on some platforms.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// A complete interactive message with text and button rows.
///
/// Used as the parameter type for `ChannelAdapter::send_interactive()`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InteractiveMessage {
    /// Message text displayed above the buttons.
    pub text: String,
    /// Rows of buttons. Each inner `Vec` is rendered as a horizontal row.
    pub buttons: Vec<Vec<InteractiveButton>>,
}

/// Content types that can be received from a channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ChannelContent {
    Text(String),
    Image {
        url: String,
        caption: Option<String>,
        /// MIME type of the image (e.g. `image/jpeg`, `image/png`).
        /// When present, this is passed through to the vision/LLM layer so that
        /// the correct media type is used instead of the generic
        /// `application/octet-stream` default.
        #[serde(default)]
        mime_type: Option<String>,
    },
    File {
        url: String,
        filename: String,
    },
    /// Local file data (bytes read from disk). Used by the proactive `channel_send`
    /// tool when `file_path` is provided instead of `file_url`.
    FileData {
        data: Vec<u8>,
        filename: String,
        mime_type: String,
    },
    Voice {
        url: String,
        caption: Option<String>,
        duration_seconds: u32,
    },
    Video {
        url: String,
        caption: Option<String>,
        duration_seconds: u32,
        filename: Option<String>,
    },
    Location {
        lat: f64,
        lon: f64,
    },
    Command {
        name: String,
        args: Vec<String>,
    },
    /// Interactive message with buttons (inline keyboards, block actions, etc.).
    ///
    /// Used by Telegram inline keyboards, Slack Block Kit actions, and Feishu
    /// interactive cards. The `buttons` field is a list of rows, where each row
    /// contains one or more buttons.
    Interactive {
        text: String,
        buttons: Vec<Vec<InteractiveButton>>,
    },
    /// A callback from a user clicking an interactive button.
    ///
    /// Generated by Telegram `callback_query`, Slack `block_actions`, or
    /// Feishu `card.action.trigger` events. The `action` field contains the
    /// callback data string set when the button was created.
    ButtonCallback {
        action: String,
        /// Original message text (if available).
        message_text: Option<String>,
    },
}

/// A unified message from any channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelMessage {
    /// Which channel this came from.
    pub channel: ChannelType,
    /// Platform-specific message identifier.
    pub platform_message_id: String,
    /// Who sent this message.
    pub sender: ChannelUser,
    /// The message content.
    pub content: ChannelContent,
    /// Optional target agent (if routed directly).
    pub target_agent: Option<AgentId>,
    /// When the message was sent.
    pub timestamp: DateTime<Utc>,
    /// Whether this message is from a group chat (vs DM).
    #[serde(default)]
    pub is_group: bool,
    /// Thread ID for threaded conversations (platform-specific).
    #[serde(default)]
    pub thread_id: Option<String>,
    /// Arbitrary platform metadata.
    pub metadata: HashMap<String, serde_json::Value>,
}

/// Sender identity context passed from channels to the kernel.
///
/// Carries enough information for agents to know who is talking to them
/// and from which channel, without depending on kernel-level types.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SenderContext {
    /// Channel name (e.g. "telegram", "discord", "slack").
    pub channel: String,
    /// Platform-specific user ID.
    pub user_id: String,
    /// Human-readable display name.
    pub display_name: String,
    /// Whether the message came from a group chat (vs DM).
    #[serde(default)]
    pub is_group: bool,
    /// Whether the bot was @mentioned in this message.
    #[serde(default)]
    pub was_mentioned: bool,
    /// Thread ID for threaded conversations (platform-specific).
    #[serde(default)]
    pub thread_id: Option<String>,
    /// Account ID for multi-bot deployments on the same channel.
    #[serde(default)]
    pub account_id: Option<String>,
    /// Auto-routing strategy configured for this channel.
    #[serde(default)]
    pub auto_route: AutoRouteStrategy,
    /// TTL in minutes for the `sticky_ttl` auto-routing strategy.
    #[serde(default)]
    pub auto_route_ttl_minutes: u32,
    /// Minimum heuristic confidence threshold for `sticky_heuristic` strategy.
    #[serde(default)]
    pub auto_route_confidence_threshold: u32,
    /// Sticky bonus score for `sticky_heuristic` strategy.
    #[serde(default)]
    pub auto_route_sticky_bonus: u32,
    /// Divergence count threshold for `sticky_heuristic` strategy.
    #[serde(default)]
    pub auto_route_divergence_count: u32,
    /// The bot's own platform `@handle` on this channel (e.g. `fandangorodelo_bot`
    /// on Telegram). Used so the agent knows its own alias in the prompt.
    #[serde(default)]
    pub bot_username: Option<String>,
    /// The current sender's `@handle` on the platform, when available.
    #[serde(default)]
    pub sender_username: Option<String>,
    /// Known members of the group chat where this message was sent.
    /// Empty for DMs and for the very first message in a group before the
    /// roster has accumulated any entries.
    #[serde(default)]
    pub group_members: Vec<GroupMember>,
    /// Platform chat/conversation ID. For Telegram this is the group chat_id
    /// (negative for groups) or user_id for DMs. Used by the roster store as
    /// part of the key.
    #[serde(default)]
    pub chat_id: Option<String>,
}

/// Agent lifecycle phase for UX indicators.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum AgentPhase {
    /// Message is queued, waiting for agent.
    Queued,
    /// Agent is calling the LLM.
    Thinking,
    /// Agent is executing a tool.
    ToolUse {
        /// Tool being executed (max 64 chars, sanitized).
        tool_name: String,
    },
    /// Agent is streaming tokens.
    Streaming,
    /// Agent finished successfully.
    Done,
    /// Agent encountered an error.
    Error,
}

impl AgentPhase {
    /// Sanitize a tool name for display (truncate to 64 chars, strip control chars).
    #[inline]
    pub fn tool_use(name: &str) -> Self {
        let sanitized: String = name.chars().filter(|c| !c.is_control()).take(64).collect();
        Self::ToolUse {
            tool_name: sanitized,
        }
    }
}

/// Reaction to show in a channel (emoji-based).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LifecycleReaction {
    /// The agent phase this reaction represents.
    pub phase: AgentPhase,
    /// Channel-appropriate emoji.
    pub emoji: String,
    /// Whether to remove the previous phase reaction.
    pub remove_previous: bool,
}

/// Hardcoded emoji allowlist for lifecycle reactions.
pub const ALLOWED_REACTION_EMOJI: &[&str] = &[
    "\u{1F914}",        // 🤔 thinking
    "\u{2699}\u{FE0F}", // ⚙️ tool_use
    "\u{270D}\u{FE0F}", // ✍️ streaming
    "\u{2705}",         // ✅ done
    "\u{274C}",         // ❌ error
    "\u{23F3}",         // ⏳ queued
    "\u{1F504}",        // 🔄 processing
    "\u{1F440}",        // 👀 looking
];

/// Get the default emoji for a given agent phase.
#[inline]
pub fn default_phase_emoji(phase: &AgentPhase) -> &'static str {
    match phase {
        AgentPhase::Queued => "\u{23F3}",                 // ⏳
        AgentPhase::Thinking => "\u{1F914}",              // 🤔
        AgentPhase::ToolUse { .. } => "\u{2699}\u{FE0F}", // ⚙️
        AgentPhase::Streaming => "\u{270D}\u{FE0F}",      // ✍️
        AgentPhase::Done => "\u{2705}",                   // ✅
        AgentPhase::Error => "\u{274C}",                  // ❌
    }
}

/// Delivery status for outbound messages.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum DeliveryStatus {
    /// Message was sent to the channel API.
    Sent,
    /// Message was confirmed delivered to recipient.
    Delivered,
    /// Message delivery failed.
    Failed,
    /// Best-effort delivery (no confirmation available).
    BestEffort,
}

/// Receipt tracking outbound message delivery.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryReceipt {
    /// Platform message ID (if available).
    pub message_id: String,
    /// Channel type this was sent through.
    pub channel: String,
    /// Sanitized recipient identifier (no PII).
    pub recipient: String,
    /// Delivery status.
    pub status: DeliveryStatus,
    /// When the delivery attempt occurred.
    pub timestamp: DateTime<Utc>,
    /// Error message (if failed — sanitized, no credentials).
    pub error: Option<String>,
}

/// Health status for a channel adapter.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ChannelStatus {
    /// Whether the adapter is currently connected/running.
    pub connected: bool,
    /// When the adapter was started (ISO 8601).
    pub started_at: Option<DateTime<Utc>>,
    /// When the last message was received.
    pub last_message_at: Option<DateTime<Utc>>,
    /// Total messages received since start.
    pub messages_received: u64,
    /// Total messages sent since start.
    pub messages_sent: u64,
    /// Last error message (if any).
    pub last_error: Option<String>,
}

// Re-export policy/format types from librefang-types for convenience.
pub use librefang_types::config::{DmPolicy, GroupPolicy, OutputFormat};

/// Trait that every channel adapter must implement.
///
/// A channel adapter bridges a messaging platform to the LibreFang kernel by converting
/// platform-specific messages into `ChannelMessage` events and sending responses back.
#[async_trait]
pub trait ChannelAdapter: Send + Sync {
    /// Human-readable name of this adapter.
    fn name(&self) -> &str;

    /// The channel type this adapter handles.
    fn channel_type(&self) -> ChannelType;

    /// Start receiving messages. Returns a stream of incoming messages.
    async fn start(
        &self,
    ) -> Result<
        Pin<Box<dyn Stream<Item = ChannelMessage> + Send>>,
        Box<dyn std::error::Error + Send + Sync>,
    >;

    /// Send a response back to a user on this channel.
    async fn send(
        &self,
        user: &ChannelUser,
        content: ChannelContent,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>>;

    /// Send a typing indicator (optional — default no-op).
    async fn send_typing(
        &self,
        _user: &ChannelUser,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Ok(())
    }

    /// Send a lifecycle reaction to a message (optional — default no-op).
    async fn send_reaction(
        &self,
        _user: &ChannelUser,
        _message_id: &str,
        _reaction: &LifecycleReaction,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Ok(())
    }

    /// Send an interactive message with buttons to a user.
    ///
    /// Platforms that support interactive messages (Telegram inline keyboards,
    /// Slack Block Kit, Feishu cards) should override this. The default
    /// implementation falls back to sending plain text with button labels
    /// listed as a hint.
    async fn send_interactive(
        &self,
        user: &ChannelUser,
        message: &InteractiveMessage,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        // Fallback: render buttons as text hints
        let mut text = message.text.clone();
        for row in &message.buttons {
            text.push('\n');
            for btn in row {
                text.push_str(&format!("  [{}]", btn.label));
            }
        }
        self.send(user, ChannelContent::Text(text)).await
    }

    /// Whether error messages should be suppressed (logged only) instead of
    /// posted publicly. Adapters where replies are visible to all followers
    /// (e.g. Mastodon) should return `true` to avoid leaking internal errors.
    fn suppress_error_responses(&self) -> bool {
        false
    }

    /// Build webhook routes for mounting on the shared HTTP server.
    ///
    /// Adapters that handle incoming messages via HTTP webhooks (e.g. Feishu,
    /// Teams, DingTalk) should implement this method instead of spawning their
    /// own HTTP server inside `start()`.
    ///
    /// Returns `(axum::Router, message_stream)`. The router will be nested
    /// under `/channels/{adapter_name}` on the main API server. The stream
    /// yields parsed `ChannelMessage` items exactly like `start()` does.
    ///
    /// When this method returns `Some`, `start()` should return an empty stream
    /// (the BridgeManager will use the stream returned here instead).
    async fn create_webhook_routes(
        &self,
    ) -> Option<(
        axum::Router,
        Pin<Box<dyn Stream<Item = ChannelMessage> + Send>>,
    )> {
        None
    }

    /// Stop the adapter and clean up resources.
    async fn stop(&self) -> Result<(), Box<dyn std::error::Error + Send + Sync>>;

    /// Get the current health status of this adapter (optional — default returns disconnected).
    fn status(&self) -> ChannelStatus {
        ChannelStatus::default()
    }

    /// Get a stream of typing indicator events (optional — default returns None).
    fn typing_events(&self) -> Option<mpsc::Receiver<TypingEvent>> {
        None
    }

    /// Send a response as a thread reply (optional — default falls back to `send()`).
    async fn send_in_thread(
        &self,
        user: &ChannelUser,
        content: ChannelContent,
        _thread_id: &str,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.send(user, content).await
    }

    /// Whether this adapter supports streaming output (progressive message updates).
    ///
    /// When true, the bridge will use `send_streaming()` instead of `send()` for
    /// agent responses, enabling real-time token display.
    fn supports_streaming(&self) -> bool {
        false
    }

    /// Stream a response progressively by consuming text deltas from a channel.
    ///
    /// For adapters that support streaming (e.g. Telegram), this sends an initial
    /// placeholder message, then edits it in-place as new tokens arrive. The
    /// `thread_id` is used for forum-topic replies on supported platforms.
    ///
    /// The `delta_rx` receiver is consumed (ownership transfer) — the adapter
    /// reads deltas until the channel closes. On error, delivery is partial:
    /// tokens already sent to the user are not retracted. The bridge layer
    /// buffers deltas and will fall back to a non-streaming `send()` if this
    /// method returns an error.
    ///
    /// Default implementation collects all deltas and sends as a single message.
    async fn send_streaming(
        &self,
        user: &ChannelUser,
        mut delta_rx: mpsc::Receiver<String>,
        _thread_id: Option<&str>,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let mut full_text = String::new();
        while let Some(delta) = delta_rx.recv().await {
            full_text.push_str(&delta);
        }
        if !full_text.is_empty() {
            self.send(user, ChannelContent::Text(full_text)).await?;
        }
        Ok(())
    }
}

/// Split a message into chunks of at most `max_len` characters,
/// preferring to split at newline boundaries.
///
/// HTML-entity-aware: never cuts in the middle of `&...;` sequences
/// (e.g. `&amp;`, `&lt;`, `&#123;`).
///
/// Shared utility used by Telegram, Discord, and Slack adapters.
#[inline]
pub fn split_message(text: &str, max_len: usize) -> Vec<&str> {
    if text.len() <= max_len {
        return vec![text];
    }
    let mut chunks = Vec::new();
    let mut remaining = text;
    while !remaining.is_empty() {
        if remaining.len() <= max_len {
            chunks.push(remaining);
            break;
        }
        // Try to split at a newline near the boundary (UTF-8 safe)
        let safe_end = librefang_types::truncate_str(remaining, max_len).len();
        // Avoid splitting inside an HTML entity (`&...;`).  Walk backwards
        // from safe_end: if we find `&` without a subsequent `;` before the
        // boundary, move the split point to just before that `&`.
        let safe_end = retreat_past_html_entity(remaining, safe_end);
        let split_at = remaining[..safe_end].rfind('\n').unwrap_or(safe_end);
        let (chunk, rest) = remaining.split_at(split_at);
        chunks.push(chunk);
        // Skip the newline (and optional \r) we split on
        remaining = rest
            .strip_prefix("\r\n")
            .or_else(|| rest.strip_prefix('\n'))
            .unwrap_or(rest);
    }
    chunks
}

/// If `pos` falls inside an HTML entity (`&...;`), return the index of the
/// `&` so the caller splits before it.  Otherwise return `pos` unchanged.
///
/// HTML entities are at most ~10 chars long (`&#1114111;`), so we only
/// look back a small window.
fn retreat_past_html_entity(text: &str, pos: usize) -> usize {
    // Maximum entity length we consider (e.g. `&#1114111;` = 10 chars).
    const MAX_ENTITY_LEN: usize = 12;
    let raw_start = pos.saturating_sub(MAX_ENTITY_LEN);
    // Snap to the nearest char boundary so we never slice inside a multi-byte
    // UTF-8 sequence (e.g. `ñ` = 2 bytes, emoji = 4 bytes). Without this,
    // text containing non-ASCII characters panics on the `text[start..pos]`
    // slice below. See #2285.
    let search_start = (raw_start..=pos)
        .find(|&i| text.is_char_boundary(i))
        .unwrap_or(pos);
    if search_start >= pos {
        return pos;
    }
    // Look for the last `&` in the window ending at `pos`.
    if let Some(rel) = text[search_start..pos].rfind('&') {
        let amp_pos = search_start + rel;
        // Check whether there is a matching `;` between the `&` and `pos`.
        // If not, we are inside an incomplete entity — retreat to `amp_pos`.
        if !text[amp_pos..pos].contains(';') {
            return amp_pos;
        }
    }
    pos
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_channel_message_serialization() {
        let msg = ChannelMessage {
            channel: ChannelType::Telegram,
            platform_message_id: "123".to_string(),
            sender: ChannelUser {
                platform_id: "user1".to_string(),
                display_name: "Alice".to_string(),
                librefang_user: None,
            },
            content: ChannelContent::Text("Hello!".to_string()),
            target_agent: None,
            timestamp: Utc::now(),
            is_group: false,
            thread_id: None,
            metadata: HashMap::new(),
        };

        let json = serde_json::to_string(&msg).unwrap();
        let deserialized: ChannelMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.channel, ChannelType::Telegram);
    }

    #[test]
    fn test_split_message_short() {
        assert_eq!(split_message("hello", 100), vec!["hello"]);
    }

    #[test]
    fn test_split_message_at_newlines() {
        let text = "line1\nline2\nline3";
        let chunks = split_message(text, 10);
        assert_eq!(chunks, vec!["line1", "line2", "line3"]);
    }

    #[test]
    fn test_split_message_multibyte_utf8_no_panic() {
        // Regression test for #2285: retreat_past_html_entity panicked when
        // search_start landed inside a multi-byte char like ñ (2 bytes).
        // Build a string where ñ straddles the max_len - 12 boundary.
        let text = "coño ".repeat(300); // 1500 chars, plenty of ñ near any boundary
        let chunks = split_message(&text, 50);
        assert!(!chunks.is_empty());
        // Verify all chunks are valid UTF-8 (implicit — they're &str)
        for chunk in &chunks {
            assert!(chunk.len() <= 50);
        }
    }

    #[test]
    fn test_split_message_emoji_no_panic() {
        // Emoji are 4 bytes in UTF-8 — even more fragile than ñ.
        let text = "hello 😀 ".repeat(200);
        let chunks = split_message(&text, 40);
        assert!(!chunks.is_empty());
        for chunk in &chunks {
            assert!(chunk.len() <= 40);
        }
    }

    #[test]
    fn test_retreat_past_html_entity_multibyte_safe() {
        // Direct test: pos just after a ñ, search window crosses into it.
        let text = "aaaaaaaaañbbbbb"; // ñ at byte 9-10
        let result = retreat_past_html_entity(text, 11);
        // Should not panic, and should return 11 (no & found)
        assert_eq!(result, 11);
    }

    #[test]
    fn test_channel_type_matrix_serde() {
        let ct = ChannelType::Matrix;
        let json = serde_json::to_string(&ct).unwrap();
        let back: ChannelType = serde_json::from_str(&json).unwrap();
        assert_eq!(back, ChannelType::Matrix);
    }

    #[test]
    fn test_channel_type_email_serde() {
        let ct = ChannelType::Email;
        let json = serde_json::to_string(&ct).unwrap();
        let back: ChannelType = serde_json::from_str(&json).unwrap();
        assert_eq!(back, ChannelType::Email);
    }

    #[test]
    fn test_channel_content_variants() {
        let text = ChannelContent::Text("hello".to_string());
        let cmd = ChannelContent::Command {
            name: "status".to_string(),
            args: vec![],
        };
        let loc = ChannelContent::Location {
            lat: 40.7128,
            lon: -74.0060,
        };
        let video = ChannelContent::Video {
            url: "https://example.com/video.mp4".to_string(),
            caption: Some("my video".to_string()),
            duration_seconds: 30,
            filename: Some("video.mp4".to_string()),
        };

        let interactive = ChannelContent::Interactive {
            text: "Choose an option:".to_string(),
            buttons: vec![vec![
                InteractiveButton {
                    label: "Approve".to_string(),
                    action: "approve_123".to_string(),
                    style: Some("primary".to_string()),
                    url: None,
                },
                InteractiveButton {
                    label: "Deny".to_string(),
                    action: "deny_123".to_string(),
                    style: Some("danger".to_string()),
                    url: None,
                },
            ]],
        };

        let callback = ChannelContent::ButtonCallback {
            action: "approve_123".to_string(),
            message_text: Some("Choose an option:".to_string()),
        };

        // Just verify they serialize without panic
        serde_json::to_string(&text).unwrap();
        serde_json::to_string(&cmd).unwrap();
        serde_json::to_string(&loc).unwrap();
        serde_json::to_string(&video).unwrap();
        serde_json::to_string(&interactive).unwrap();
        serde_json::to_string(&callback).unwrap();
    }

    #[test]
    fn test_interactive_button_serde_roundtrip() {
        let btn = InteractiveButton {
            label: "Click me".to_string(),
            action: "do_thing".to_string(),
            style: Some("primary".to_string()),
            url: None,
        };
        let json = serde_json::to_string(&btn).unwrap();
        let back: InteractiveButton = serde_json::from_str(&json).unwrap();
        assert_eq!(back.label, "Click me");
        assert_eq!(back.action, "do_thing");
        assert_eq!(back.style, Some("primary".to_string()));
        assert!(back.url.is_none());
    }

    #[test]
    fn test_interactive_button_url_variant() {
        let btn = InteractiveButton {
            label: "Open link".to_string(),
            action: String::new(),
            style: None,
            url: Some("https://example.com".to_string()),
        };
        let json = serde_json::to_string(&btn).unwrap();
        assert!(json.contains("https://example.com"));
        // `style` should be skipped when None
        assert!(!json.contains("style"));
    }

    #[test]
    fn test_interactive_message_serde_roundtrip() {
        let msg = InteractiveMessage {
            text: "Pick one:".to_string(),
            buttons: vec![
                vec![
                    InteractiveButton {
                        label: "A".to_string(),
                        action: "pick_a".to_string(),
                        style: None,
                        url: None,
                    },
                    InteractiveButton {
                        label: "B".to_string(),
                        action: "pick_b".to_string(),
                        style: None,
                        url: None,
                    },
                ],
                vec![InteractiveButton {
                    label: "C".to_string(),
                    action: "pick_c".to_string(),
                    style: Some("danger".to_string()),
                    url: None,
                }],
            ],
        };
        let json = serde_json::to_string(&msg).unwrap();
        let back: InteractiveMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(back.text, "Pick one:");
        assert_eq!(back.buttons.len(), 2);
        assert_eq!(back.buttons[0].len(), 2);
        assert_eq!(back.buttons[1].len(), 1);
        assert_eq!(back.buttons[1][0].label, "C");
    }

    #[test]
    fn test_channel_content_interactive_serde() {
        let content = ChannelContent::Interactive {
            text: "Approve request?".to_string(),
            buttons: vec![vec![
                InteractiveButton {
                    label: "Yes".to_string(),
                    action: "approve".to_string(),
                    style: Some("primary".to_string()),
                    url: None,
                },
                InteractiveButton {
                    label: "No".to_string(),
                    action: "reject".to_string(),
                    style: Some("danger".to_string()),
                    url: None,
                },
            ]],
        };
        let json = serde_json::to_string(&content).unwrap();
        let back: ChannelContent = serde_json::from_str(&json).unwrap();
        match back {
            ChannelContent::Interactive { text, buttons } => {
                assert_eq!(text, "Approve request?");
                assert_eq!(buttons.len(), 1);
                assert_eq!(buttons[0].len(), 2);
                assert_eq!(buttons[0][0].action, "approve");
            }
            other => panic!("Expected Interactive, got {other:?}"),
        }
    }

    #[test]
    fn test_channel_content_button_callback_serde() {
        let content = ChannelContent::ButtonCallback {
            action: "approve_456".to_string(),
            message_text: Some("Original message".to_string()),
        };
        let json = serde_json::to_string(&content).unwrap();
        let back: ChannelContent = serde_json::from_str(&json).unwrap();
        match back {
            ChannelContent::ButtonCallback {
                action,
                message_text,
            } => {
                assert_eq!(action, "approve_456");
                assert_eq!(message_text, Some("Original message".to_string()));
            }
            other => panic!("Expected ButtonCallback, got {other:?}"),
        }
    }

    // ----- AgentPhase tests -----

    #[test]
    fn test_agent_phase_serde_roundtrip() {
        let phases = vec![
            AgentPhase::Queued,
            AgentPhase::Thinking,
            AgentPhase::tool_use("web_fetch"),
            AgentPhase::Streaming,
            AgentPhase::Done,
            AgentPhase::Error,
        ];
        for phase in &phases {
            let json = serde_json::to_string(phase).unwrap();
            let back: AgentPhase = serde_json::from_str(&json).unwrap();
            assert_eq!(*phase, back);
        }
    }

    #[test]
    fn test_agent_phase_tool_use_sanitizes() {
        let phase = AgentPhase::tool_use("hello\x00world\x01test");
        if let AgentPhase::ToolUse { tool_name } = phase {
            assert!(!tool_name.contains('\x00'));
            assert!(!tool_name.contains('\x01'));
            assert!(tool_name.contains("hello"));
        } else {
            panic!("Expected ToolUse variant");
        }
    }

    #[test]
    fn test_agent_phase_tool_use_truncates_long_name() {
        let long_name = "a".repeat(200);
        let phase = AgentPhase::tool_use(&long_name);
        if let AgentPhase::ToolUse { tool_name } = phase {
            assert!(tool_name.len() <= 64);
        }
    }

    #[test]
    fn test_default_phase_emoji() {
        assert_eq!(default_phase_emoji(&AgentPhase::Thinking), "\u{1F914}");
        assert_eq!(default_phase_emoji(&AgentPhase::Done), "\u{2705}");
        assert_eq!(default_phase_emoji(&AgentPhase::Error), "\u{274C}");
    }

    // ----- DeliveryReceipt tests -----

    #[test]
    fn test_delivery_status_serde() {
        let statuses = vec![
            DeliveryStatus::Sent,
            DeliveryStatus::Delivered,
            DeliveryStatus::Failed,
            DeliveryStatus::BestEffort,
        ];
        for status in &statuses {
            let json = serde_json::to_string(status).unwrap();
            let back: DeliveryStatus = serde_json::from_str(&json).unwrap();
            assert_eq!(*status, back);
        }
    }

    #[test]
    fn test_delivery_receipt_serde() {
        let receipt = DeliveryReceipt {
            message_id: "msg-123".to_string(),
            channel: "telegram".to_string(),
            recipient: "user-456".to_string(),
            status: DeliveryStatus::Sent,
            timestamp: Utc::now(),
            error: None,
        };
        let json = serde_json::to_string(&receipt).unwrap();
        let back: DeliveryReceipt = serde_json::from_str(&json).unwrap();
        assert_eq!(back.message_id, "msg-123");
        assert_eq!(back.status, DeliveryStatus::Sent);
    }

    #[test]
    fn test_delivery_receipt_with_error() {
        let receipt = DeliveryReceipt {
            message_id: "msg-789".to_string(),
            channel: "slack".to_string(),
            recipient: "channel-abc".to_string(),
            status: DeliveryStatus::Failed,
            timestamp: Utc::now(),
            error: Some("Connection refused".to_string()),
        };
        let json = serde_json::to_string(&receipt).unwrap();
        assert!(json.contains("Connection refused"));
    }
}
