//! Media understanding engine — image description, audio transcription, video analysis.
//!
//! Auto-cascades through available providers based on configured API keys.

use librefang_types::media::{
    MediaAttachment, MediaConfig, MediaSource, MediaType, MediaUnderstanding,
};
use std::path::Path;
use std::sync::Arc;
use tokio::io::AsyncWriteExt;
use tokio::sync::Semaphore;
use tracing::info;

/// Media understanding engine.
pub struct MediaEngine {
    config: MediaConfig,
    semaphore: Arc<Semaphore>,
}

impl MediaEngine {
    pub fn new(config: MediaConfig) -> Self {
        let max = config.max_concurrency.clamp(1, 8);
        Self {
            config,
            semaphore: Arc::new(Semaphore::new(max)),
        }
    }

    /// Describe an image using a vision-capable LLM.
    /// Auto-cascade: Anthropic -> OpenAI -> Gemini (based on API key availability).
    pub async fn describe_image(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Image {
            return Err("Expected image attachment".into());
        }

        // Determine which provider to use
        let provider = self.config.image_provider.as_deref()
            .or_else(|| detect_vision_provider())
            .ok_or("No vision-capable LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY")?;

        // For now, return a structured result indicating the provider.
        // Actual API call would go here using reqwest.
        Ok(MediaUnderstanding {
            media_type: MediaType::Image,
            description: format!(
                "[Image description would be generated by {} provider]",
                provider
            ),
            provider: provider.to_string(),
            model: default_vision_model(provider).to_string(),
        })
    }

    /// Transcribe audio using speech-to-text.
    /// Auto-cascade: Groq (whisper-large-v3-turbo) -> OpenAI (whisper-1).
    pub async fn transcribe_audio(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Audio {
            return Err("Expected audio attachment".into());
        }

        let explicit = self.config.audio_provider.is_some();
        let provider = self
            .config
            .audio_provider
            .as_deref()
            .or_else(|| detect_audio_provider())
            .ok_or(
                "No audio transcription provider configured. Set [media] audio_provider in config.toml.",
            )?;

        if !explicit {
            tracing::warn!(
                detected_provider = provider,
                "Audio provider auto-detected from env var — may not match actual service. \
                 Set [media] audio_provider in config.toml for reliable STT."
            );
        }

        let _permit = self.semaphore.acquire().await.map_err(|e| e.to_string())?;

        // Read audio bytes from source
        let mut audio_bytes = match &attachment.source {
            MediaSource::FilePath { path } => tokio::fs::read(path)
                .await
                .map_err(|e| format!("Failed to read audio file '{}': {}", path, e))?,
            MediaSource::Base64 { data, .. } => {
                use base64::Engine;
                base64::engine::general_purpose::STANDARD
                    .decode(data)
                    .map_err(|e| format!("Failed to decode base64 audio: {}", e))?
            }
            MediaSource::Url { url } => {
                return Err(format!(
                    "URL-based audio source not supported for transcription: {}",
                    url
                ));
            }
        };

        // Derive a proper filename with extension for Whisper to detect format.
        let source_ext = match &attachment.source {
            MediaSource::FilePath { path } => Path::new(path)
                .extension()
                .and_then(|e| e.to_str())
                .map(|s| s.to_ascii_lowercase()),
            _ => None,
        };
        let mut mime = attachment.mime_type.clone();
        let mut ext = mime_to_ext(&mime).unwrap_or_else(|| {
            // Fall back to the source file extension when the MIME is missing
            // or unknown (e.g. `application/octet-stream`).
            source_ext.clone().unwrap_or_else(|| "wav".to_string())
        });

        // Telegram voice notes arrive as `.oga` / `audio/oga`. Whisper's
        // format probe rejects both — re-encode to Ogg/Opus so the same
        // Opus payload is delivered under the `audio/ogg` shape Whisper
        // accepts. Failure here is hard-error: the warn+passthrough
        // fallback is useless (the bug this fixes is exactly that raw
        // .oga is rejected).
        if ext == "oga" || mime.eq_ignore_ascii_case("audio/oga") {
            let transcoded = transcode_oga_to_ogg_opus(&audio_bytes)
                .await
                .map_err(|e| format!("ffmpeg .oga transcode failed: {e}"))?;
            info!(
                original_size = audio_bytes.len(),
                transcoded_size = transcoded.len(),
                "Transcoded .oga -> .ogg before Whisper upload"
            );
            audio_bytes = transcoded;
            ext = "ogg".to_string();
            mime = "audio/ogg".to_string();
        }

        let filename = format!("audio.{}", ext);

        let model = self
            .config
            .audio_model
            .as_deref()
            .unwrap_or_else(|| default_audio_model(provider));

        info!(provider, model, filename = %filename, size = audio_bytes.len(), "Sending audio for transcription");

        let transcription = match provider {
            // Whisper-compatible providers (OpenAI multipart protocol)
            "groq" | "openai" | "minimax" | "fireworks" | "together" | "siliconflow" => {
                let (api_url, api_key) = whisper_provider_config(provider)?;
                whisper_transcribe(&api_url, &api_key, model, audio_bytes, &filename, &mime).await?
            }
            // Gemini — multimodal content generation with audio input
            "gemini" => gemini_transcribe(model, audio_bytes, &mime).await?,
            // ElevenLabs — Speech-to-Text API
            "elevenlabs" => elevenlabs_transcribe(model, audio_bytes, &mime).await?,
            other => return Err(format!("Unsupported audio provider: {}", other)),
        };

        let transcription = transcription.trim().to_string();
        if transcription.is_empty() {
            return Err("Transcription returned empty text".into());
        }

        info!(
            provider,
            model,
            chars = transcription.len(),
            "Audio transcription complete"
        );

        Ok(MediaUnderstanding {
            media_type: MediaType::Audio,
            description: transcription,
            provider: provider.to_string(),
            model: model.to_string(),
        })
    }

    /// Describe video using Gemini.
    pub async fn describe_video(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Video {
            return Err("Expected video attachment".into());
        }

        if !self.config.video_description {
            return Err("Video description is disabled in configuration".into());
        }

        if std::env::var("GEMINI_API_KEY").is_err() && std::env::var("GOOGLE_API_KEY").is_err() {
            return Err("Video description requires GEMINI_API_KEY or GOOGLE_API_KEY".into());
        }

        Ok(MediaUnderstanding {
            media_type: MediaType::Video,
            description: "[Video description would be generated by Gemini]".to_string(),
            provider: "gemini".to_string(),
            model: "gemini-2.5-flash".to_string(),
        })
    }

    /// Process multiple attachments concurrently (bounded by max_concurrency).
    pub async fn process_attachments(
        &self,
        attachments: Vec<MediaAttachment>,
    ) -> Vec<Result<MediaUnderstanding, String>> {
        let mut handles = Vec::new();

        for attachment in attachments {
            // Skip media types that are disabled in config
            match attachment.media_type {
                MediaType::Image if !self.config.image_description => {
                    continue;
                }
                MediaType::Audio if !self.config.audio_transcription => {
                    continue;
                }
                MediaType::Video if !self.config.video_description => {
                    continue;
                }
                _ => {}
            }

            let sem = self.semaphore.clone();
            let config = self.config.clone();
            let handle = tokio::spawn(async move {
                let _permit = sem.acquire().await.map_err(|e| e.to_string())?;
                let engine = MediaEngine {
                    config,
                    semaphore: Arc::new(Semaphore::new(1)), // inner engine, no extra semaphore
                };
                match attachment.media_type {
                    MediaType::Image => engine.describe_image(&attachment).await,
                    MediaType::Audio => engine.transcribe_audio(&attachment).await,
                    MediaType::Video => engine.describe_video(&attachment).await,
                }
            });
            handles.push(handle);
        }

        let mut results = Vec::new();
        for handle in handles {
            match handle.await {
                Ok(result) => results.push(result),
                Err(e) => results.push(Err(format!("Task failed: {e}"))),
            }
        }
        results
    }
}

/// Detect which vision provider is available based on environment variables.
fn detect_vision_provider() -> Option<&'static str> {
    let has_key = |var: &str| std::env::var(var).is_ok_and(|v| !v.trim().is_empty());
    if has_key("ANTHROPIC_API_KEY") {
        return Some("anthropic");
    }
    if has_key("OPENAI_API_KEY") {
        return Some("openai");
    }
    if has_key("GEMINI_API_KEY") || has_key("GOOGLE_API_KEY") {
        return Some("gemini");
    }
    None
}

// ── STT provider helpers ──────────────────────────────────────────────

/// Resolve Whisper-compatible API URL and key for a provider.
fn whisper_provider_config(provider: &str) -> Result<(String, String), String> {
    match provider {
        "groq" => Ok((
            "https://api.groq.com/openai/v1/audio/transcriptions".into(),
            std::env::var("GROQ_API_KEY").map_err(|_| "GROQ_API_KEY not set")?,
        )),
        "openai" => Ok((
            "https://api.openai.com/v1/audio/transcriptions".into(),
            std::env::var("OPENAI_API_KEY").map_err(|_| "OPENAI_API_KEY not set")?,
        )),
        "minimax" => Ok((
            "https://api.minimax.io/v1/audio/transcriptions".into(),
            std::env::var("MINIMAX_API_KEY")
                .or_else(|_| std::env::var("MINIMAX_CN_API_KEY"))
                .map_err(|_| "MINIMAX_API_KEY not set")?,
        )),
        "fireworks" => Ok((
            "https://api.fireworks.ai/inference/v1/audio/transcriptions".into(),
            std::env::var("FIREWORKS_API_KEY").map_err(|_| "FIREWORKS_API_KEY not set")?,
        )),
        "together" => Ok((
            "https://api.together.xyz/v1/audio/transcriptions".into(),
            std::env::var("TOGETHER_API_KEY").map_err(|_| "TOGETHER_API_KEY not set")?,
        )),
        "siliconflow" => Ok((
            "https://api.siliconflow.cn/v1/audio/transcriptions".into(),
            std::env::var("SILICONFLOW_API_KEY").map_err(|_| "SILICONFLOW_API_KEY not set")?,
        )),
        other => Err(format!("Unknown Whisper-compatible provider: {other}")),
    }
}

/// Transcribe using an OpenAI-compatible Whisper endpoint.
async fn whisper_transcribe(
    api_url: &str,
    api_key: &str,
    model: &str,
    audio_bytes: Vec<u8>,
    filename: &str,
    mime: &str,
) -> Result<String, String> {
    let file_part = reqwest::multipart::Part::bytes(audio_bytes)
        .file_name(filename.to_string())
        .mime_str(mime)
        .map_err(|e| format!("Failed to set MIME type: {}", e))?;

    let form = reqwest::multipart::Form::new()
        .part("file", file_part)
        .text("model", model.to_string())
        .text("response_format", "text");

    let client = crate::http_client::proxied_client();
    let resp = client
        .post(api_url)
        .bearer_auth(api_key)
        .multipart(form)
        .timeout(std::time::Duration::from_secs(60))
        .send()
        .await
        .map_err(|e| format!("Transcription request failed: {}", e))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(format!("Transcription API error ({}): {}", status, body));
    }

    resp.text()
        .await
        .map_err(|e| format!("Failed to read transcription response: {}", e))
}

/// Transcribe using Gemini's multimodal generateContent API.
async fn gemini_transcribe(
    model: &str,
    audio_bytes: Vec<u8>,
    mime: &str,
) -> Result<String, String> {
    use base64::Engine;

    let api_key = std::env::var("GEMINI_API_KEY")
        .or_else(|_| std::env::var("GOOGLE_API_KEY"))
        .map_err(|_| "GEMINI_API_KEY or GOOGLE_API_KEY not set")?;

    let audio_b64 = base64::engine::general_purpose::STANDARD.encode(&audio_bytes);

    let body = serde_json::json!({
        "contents": [{
            "parts": [
                {
                    "inline_data": {
                        "mime_type": mime,
                        "data": audio_b64,
                    }
                },
                {
                    "text": "Transcribe this audio exactly as spoken. Output only the transcription text, nothing else."
                }
            ]
        }]
    });

    let url = format!(
        "https://generativelanguage.googleapis.com/v1beta/models/{}:generateContent?key={}",
        model, api_key
    );

    let client = crate::http_client::proxied_client();
    let resp = client
        .post(&url)
        .json(&body)
        .timeout(std::time::Duration::from_secs(60))
        .send()
        .await
        .map_err(|e| format!("Gemini transcription request failed: {}", e))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let err_body = resp.text().await.unwrap_or_default();
        return Err(format!("Gemini API error ({}): {}", status, err_body));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("Failed to parse Gemini response: {}", e))?;

    json["candidates"][0]["content"]["parts"][0]["text"]
        .as_str()
        .map(|s| s.to_string())
        .ok_or_else(|| "Gemini returned no transcription text".to_string())
}

/// Transcribe using ElevenLabs Speech-to-Text API.
async fn elevenlabs_transcribe(
    model: &str,
    audio_bytes: Vec<u8>,
    mime: &str,
) -> Result<String, String> {
    let api_key = std::env::var("ELEVENLABS_API_KEY").map_err(|_| "ELEVENLABS_API_KEY not set")?;

    let file_part = reqwest::multipart::Part::bytes(audio_bytes)
        .file_name("audio.webm".to_string())
        .mime_str(mime)
        .map_err(|e| format!("Failed to set MIME type: {}", e))?;

    let form = reqwest::multipart::Form::new()
        .part("file", file_part)
        .text("model_id", model.to_string());

    let client = crate::http_client::proxied_client();
    let resp = client
        .post("https://api.elevenlabs.io/v1/speech-to-text")
        .header("xi-api-key", &api_key)
        .multipart(form)
        .timeout(std::time::Duration::from_secs(60))
        .send()
        .await
        .map_err(|e| format!("ElevenLabs STT request failed: {}", e))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let err_body = resp.text().await.unwrap_or_default();
        return Err(format!("ElevenLabs API error ({}): {}", status, err_body));
    }

    let json: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("Failed to parse ElevenLabs response: {}", e))?;

    json["text"]
        .as_str()
        .map(|s| s.to_string())
        .ok_or_else(|| "ElevenLabs returned no transcription text".to_string())
}

/// the caller can fall back to the source file extension.
fn mime_to_ext(mime: &str) -> Option<String> {
    match mime.to_ascii_lowercase().as_str() {
        "audio/wav" | "audio/x-wav" => Some("wav".to_string()),
        "audio/mpeg" | "audio/mp3" => Some("mp3".to_string()),
        "audio/ogg" => Some("ogg".to_string()),
        "audio/webm" => Some("webm".to_string()),
        "audio/mp4" | "audio/m4a" => Some("m4a".to_string()),
        "audio/flac" => Some("flac".to_string()),
        _ => None,
    }
}

/// Re-encode `.oga` into Ogg/Opus. Input streams in via stdin, output
/// streams out of stdout — no scratch files on disk. Same Opus payload,
/// just re-packetised.
///
/// Requires `ffmpeg` on `PATH`. 30 s wall-clock cap; on timeout the child
/// is killed and reaped explicitly so there are no zombies.
async fn transcode_oga_to_ogg_opus(input_bytes: &[u8]) -> Result<Vec<u8>, String> {
    use std::process::Stdio;

    let mut child = tokio::process::Command::new("ffmpeg")
        .args([
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "ogg",
            "-i",
            "pipe:0",
            "-vn",
            "-c:a",
            "copy",
            "-f",
            "ogg",
            "pipe:1",
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            format!(
                "ffmpeg not available ({e}) — install it (brew install ffmpeg / apt install ffmpeg) to process .oga voice notes"
            )
        })?;

    // Feed stdin concurrently; hanging the write inside the main task
    // would deadlock once ffmpeg's stdout pipe buffer fills.
    if let Some(mut stdin) = child.stdin.take() {
        let bytes = input_bytes.to_vec();
        tokio::spawn(async move {
            // Writer errors are intentionally ignored: if the pipe breaks
            // (ffmpeg rejected the input or exited early), the real reason
            // surfaces on stderr and the non-zero exit code, which the
            // caller already reports. Swallowing the write error here is
            // strictly less noisy than double-reporting.
            let _ = stdin.write_all(&bytes).await;
            let _ = stdin.shutdown().await;
        });
    }

    // Read stdout / stderr concurrently with waiting so we can kill + reap
    // the child explicitly on timeout (wait_with_output would move the
    // Child handle and leak the process if the wrapping timeout fires).
    use tokio::io::AsyncReadExt;
    let mut stdout = child.stdout.take().expect("stdout piped");
    let mut stderr = child.stderr.take().expect("stderr piped");
    let stdout_task = tokio::spawn(async move {
        let mut buf = Vec::new();
        let _ = stdout.read_to_end(&mut buf).await;
        buf
    });
    let stderr_task = tokio::spawn(async move {
        let mut buf = Vec::new();
        let _ = stderr.read_to_end(&mut buf).await;
        buf
    });

    let status = match tokio::time::timeout(std::time::Duration::from_secs(30), child.wait()).await
    {
        Ok(Ok(s)) => s,
        Ok(Err(e)) => return Err(format!("ffmpeg wait failed: {e}")),
        Err(_) => {
            let _ = child.start_kill();
            let _ = child.wait().await;
            return Err("ffmpeg transcode timed out after 30s".to_string());
        }
    };

    let out = stdout_task.await.unwrap_or_default();
    let err = stderr_task.await.unwrap_or_default();

    if !status.success() {
        return Err(format!(
            "ffmpeg exited with {}: {}",
            status,
            String::from_utf8_lossy(&err).trim()
        ));
    }
    if out.is_empty() {
        return Err("ffmpeg produced an empty output stream".to_string());
    }
    Ok(out)
}

/// Detect which audio transcription provider is available.
fn detect_audio_provider() -> Option<&'static str> {
    let has_key = |var: &str| std::env::var(var).is_ok_and(|v| !v.trim().is_empty());
    if has_key("GROQ_API_KEY") {
        return Some("groq");
    }
    if has_key("OPENAI_API_KEY") {
        return Some("openai");
    }
    if has_key("GEMINI_API_KEY") || has_key("GOOGLE_API_KEY") {
        return Some("gemini");
    }
    if has_key("ELEVENLABS_API_KEY") {
        return Some("elevenlabs");
    }
    if has_key("MINIMAX_API_KEY") || has_key("MINIMAX_CN_API_KEY") {
        return Some("minimax");
    }
    if has_key("FIREWORKS_API_KEY") {
        return Some("fireworks");
    }
    if has_key("TOGETHER_API_KEY") {
        return Some("together");
    }
    if has_key("SILICONFLOW_API_KEY") {
        return Some("siliconflow");
    }
    None
}

/// Get the default vision model for a provider.
fn default_vision_model(provider: &str) -> &str {
    match provider {
        "anthropic" => "claude-sonnet-4-20250514",
        "openai" => "gpt-4o",
        "gemini" => "gemini-2.5-flash",
        _ => "unknown",
    }
}

/// Get the default audio model for a provider.
fn default_audio_model(provider: &str) -> &str {
    match provider {
        "groq" => "whisper-large-v3-turbo",
        "openai" => "whisper-1",
        "gemini" => "gemini-2.0-flash",
        "elevenlabs" => "scribe_v1",
        "minimax" => "speech-01-turbo",
        "fireworks" => "whisper-v3-turbo",
        "together" => "whisper-large-v3-turbo",
        "siliconflow" => "FunAudioLLM/SenseVoiceSmall",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use librefang_types::media::{MediaSource, MAX_IMAGE_BYTES};

    #[test]
    fn test_engine_creation() {
        let config = MediaConfig::default();
        let engine = MediaEngine::new(config);
        assert_eq!(engine.config.max_concurrency, 2);
    }

    #[test]
    fn test_engine_max_concurrency_clamped() {
        let config = MediaConfig {
            max_concurrency: 100,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        // Semaphore was clamped to 8
        assert!(engine.semaphore.available_permits() <= 8);
    }

    #[test]
    fn mime_to_ext_maps_known_types() {
        assert_eq!(mime_to_ext("audio/ogg"), Some("ogg".to_string()));
        assert_eq!(mime_to_ext("audio/mpeg"), Some("mp3".to_string()));
        assert_eq!(mime_to_ext("audio/mp3"), Some("mp3".to_string()));
        assert_eq!(mime_to_ext("audio/wav"), Some("wav".to_string()));
        assert_eq!(mime_to_ext("audio/x-wav"), Some("wav".to_string()));
        assert_eq!(mime_to_ext("audio/webm"), Some("webm".to_string()));
        assert_eq!(mime_to_ext("audio/m4a"), Some("m4a".to_string()));
        assert_eq!(mime_to_ext("audio/mp4"), Some("m4a".to_string()));
        assert_eq!(mime_to_ext("audio/flac"), Some("flac".to_string()));
    }

    #[test]
    fn mime_to_ext_is_case_insensitive() {
        assert_eq!(mime_to_ext("AUDIO/OGG"), Some("ogg".to_string()));
        assert_eq!(mime_to_ext("Audio/Mp3"), Some("mp3".to_string()));
    }

    #[test]
    fn mime_to_ext_returns_none_for_unmapped() {
        // `audio/oga` intentionally unmapped — caller handles .oga via the
        // transcode path rather than treating it as directly usable.
        assert_eq!(mime_to_ext("audio/oga"), None);
        assert_eq!(mime_to_ext("application/octet-stream"), None);
        assert_eq!(mime_to_ext(""), None);
    }

    /// Skip body when ffmpeg is absent — CI images and the production
    /// container ship with it, dev boxes may not.
    fn ffmpeg_available() -> bool {
        std::process::Command::new("ffmpeg")
            .arg("-version")
            .output()
            .is_ok()
    }

    #[tokio::test]
    async fn transcode_oga_smoke() {
        if !ffmpeg_available() {
            eprintln!("ffmpeg not on PATH — skipping");
            return;
        }
        // Synthesise a 0.5s silent Ogg/Opus buffer via ffmpeg's pipe:1,
        // then round-trip it through the transcoder. No scratch files.
        let gen = tokio::process::Command::new("ffmpeg")
            .args([
                "-hide_banner",
                "-loglevel",
                "error",
                "-f",
                "lavfi",
                "-i",
                "anullsrc=r=16000:cl=mono",
                "-t",
                "0.5",
                "-c:a",
                "libopus",
                "-f",
                "ogg",
                "pipe:1",
            ])
            .output()
            .await
            .expect("ffmpeg must run");
        assert!(
            gen.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&gen.stderr)
        );
        let input_bytes = gen.stdout;
        assert!(!input_bytes.is_empty());

        let out = transcode_oga_to_ogg_opus(&input_bytes)
            .await
            .expect("transcode must succeed on a valid Ogg/Opus");
        assert!(!out.is_empty());
        assert_eq!(&out[..4], b"OggS", "output must be an Ogg container");
    }

    #[tokio::test]
    async fn transcode_empty_input_errors() {
        if !ffmpeg_available() {
            eprintln!("ffmpeg not on PATH — skipping");
            return;
        }
        // Zero-byte input must be rejected, but ffmpeg's failure mode varies
        // across versions/platforms: newer builds exit non-zero before writing
        // any stdout ("ffmpeg exited ..."), older ones exit 0 with an empty
        // stream ("empty output"). Either is an acceptable rejection here —
        // what matters is that we don't accept the zero-byte input.
        let err = transcode_oga_to_ogg_opus(&[]).await.unwrap_err();
        assert!(
            err.contains("empty output") || err.contains("ffmpeg exited"),
            "expected ffmpeg to reject zero-byte input, got: {err}"
        );
    }

    #[tokio::test]
    async fn transcode_non_ogg_input_errors() {
        if !ffmpeg_available() {
            eprintln!("ffmpeg not on PATH — skipping");
            return;
        }
        // 256 bytes of non-Ogg junk — ffmpeg rejects the container and exits
        // non-zero before producing any stdout bytes.
        let garbage: Vec<u8> = (0..=255u8).collect();
        let err = transcode_oga_to_ogg_opus(&garbage).await.unwrap_err();
        assert!(
            err.contains("ffmpeg exited"),
            "expected ffmpeg-exit rejection, got: {err}"
        );
    }

    #[tokio::test]
    async fn test_describe_image_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::FilePath {
                path: "test.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected image"));
    }

    #[tokio::test]
    async fn test_describe_image_invalid_mime() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "application/pdf".into(),
            source: MediaSource::FilePath {
                path: "test.pdf".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_describe_image_too_large() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "big.png".into(),
            },
            size_bytes: MAX_IMAGE_BYTES + 1,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_video_disabled() {
        let config = MediaConfig {
            video_description: false,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Video,
            mime_type: "video/mp4".into(),
            source: MediaSource::FilePath {
                path: "test.mp4".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_video(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("disabled"));
    }

    #[test]
    fn test_detect_vision_provider_none() {
        // In test env, likely no API keys set — should return None.
        // (This test is environment-dependent, but safe.)
        let _ = detect_vision_provider(); // Just verify it doesn't panic
    }

    #[test]
    fn test_default_vision_models() {
        assert_eq!(
            default_vision_model("anthropic"),
            "claude-sonnet-4-20250514"
        );
        assert_eq!(default_vision_model("openai"), "gpt-4o");
        assert_eq!(default_vision_model("gemini"), "gemini-2.5-flash");
        assert_eq!(default_vision_model("unknown"), "unknown");
    }

    #[test]
    fn test_default_audio_models() {
        assert_eq!(default_audio_model("groq"), "whisper-large-v3-turbo");
        assert_eq!(default_audio_model("openai"), "whisper-1");
    }

    #[tokio::test]
    async fn test_transcribe_audio_rejects_image_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected audio"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_no_provider() {
        // With no API keys set, should fail with provider error
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "test.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        // Either fails with "No audio transcription provider" or file read error
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_url_source_rejected() {
        // URL source should be rejected
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::Url {
                url: "https://example.com/audio.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("URL-based audio source not supported"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_file_not_found() {
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "/nonexistent/path/audio.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Failed to read audio file"));
    }
}
